{% set version = "2.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bs4dash
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bs4Dash_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bs4Dash/bs4Dash_{{ version }}.tar.gz
  sha256: 1dd07a730ed19c64d1ff6fdf0f37336a0bc2358684811ccde95973c81b4c85cf

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bslib >=0.2.4
    - r-fresh
    - r-htmltools >=0.5.1.1
    - r-httpuv >=1.5.2
    - r-httr
    - r-jsonlite >=0.9.16
    - r-lifecycle
    - r-shiny >=1.6.0
    - r-waiter >=0.2.3
  run:
    - r-base
    - r-bslib >=0.2.4
    - r-fresh
    - r-htmltools >=0.5.1.1
    - r-httpuv >=1.5.2
    - r-httr
    - r-jsonlite >=0.9.16
    - r-lifecycle
    - r-shiny >=1.6.0
    - r-waiter >=0.2.3

test:
  commands:
    - $R -e "library('bs4Dash')"           # [not win]
    - "\"%R%\" -e \"library('bs4Dash')\""  # [win]

about:
  home: https://rinterface.github.io/bs4Dash/index.html, https://github.com/RinteRface/bs4Dash
  license: GPL-2.0-or-later
  summary: Make 'Bootstrap 4' dashboards. Use the full power of 'AdminLTE3', a dashboard template built on top of 'Bootstrap 4'  <https://github.com/almasaeed2010/AdminLTE/tree/v3-dev>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: bs4Dash
# Type: Package
# Title: A 'Bootstrap 4' Version of 'shinydashboard'
# Version: 0.2.0
# Authors@R: c( person("David", "Granjon", email = "dgranjon@ymail.com", role = c("aut", "cre")), person(family = "Almasaeed Studio", role = c("ctb", "cph"), comment = "AdminLTE3 theme for Bootstrap 4"), person("Winston", "Chang", role = c("ctb", "cph"), comment = "Utils functions from shinydashboard"), person("Thomas", "Park", role = c("ctb", "cph"), comment = "Bootswatch Sketchy theme CSS"))
# Maintainer: David Granjon <dgranjon@ymail.com>
# Description: Make 'Bootstrap 4' dashboards. Use the full power of 'AdminLTE3', a dashboard template built on top of 'Bootstrap 4'  <https://github.com/almasaeed2010/AdminLTE/tree/v3-dev>.
# URL: https://divadnojnarg.github.io/bs4Dash/index.html, https://github.com/DivadNojnarg/bs4Dash
# BugReports: https://github.com/DivadNojnarg/bs4Dash/issues
# License: GPL-2
# Imports: shiny, htmltools
# Suggests: plotly, shinyWidgets, knitr, rmarkdown
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.0
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-09-20 18:59:54 UTC; macdavidgranjon
# Author: David Granjon [aut, cre], Almasaeed Studio [ctb, cph] (AdminLTE3 theme for Bootstrap 4), Winston Chang [ctb, cph] (Utils functions from shinydashboard), Thomas Park [ctb, cph] (Bootswatch Sketchy theme CSS)
# Repository: CRAN
# Date/Publication: 2018-09-20 19:20:03 UTC
