travis:
  secure:
    BINSTAR_TOKEN: OJ5iSBVH6FNLfFoZ3F+KEqUyGrTdPMJqTcO0gcgJAtG8co46W7ZnEwb7a0zLIw41n9t0e2drrzmkGF6obWFht13sRQ/ZucyoV4bwmK1yQLebC4vl1l3uyeBYidZIhgefbZfHcazCju8ZT1wUxGmz/XRWQHWYafzgfYkpq1uO2cvyeiHeXbaI3IDUFMyZ3kPXuZMyp8pSimnsN0hRuBimMWxfBMlkWXoj44KF7c6Ttj2LpDIFqtEiXp3thNxZ0b9DOFAVVR9+IUWttAyNtIqtLzxt6N0Vx6uQ0SxkF7PfEyMtFJFUvcdGh1jjcvQjHyd5/qbyJZjJsbWy7kgxoHQodMflQgsdeC30pE1liXUJrC30L+QLGSM2x/TP9pqjZ0YjO2jwWckrsm7fA8MF5JT5Ad7WPQ2IYlnt20Bmmx/5NJvsVXfH7wH9cLBMESNljK6gnR5Nugi81ujXbSBIhQa7Zc3Kg77nE92i2ylDbpOmGG2YYRX0FcP7d30L52Pj/GClW7g8/oDeaENDKOsnllyMs7KZ7KnlZICecaSYPPh5s8NiG9XsSsZld2aK2Hs0ZhAKvZrUHhqZZav1R5KEdorLVwS0aYx9PovYyRWKUkXSaAiG5m5jB7uYNpHTOfly5uWt64gRm1Z+MG51o227lCr0ldI13XcMHA8iqjpFqob1X0I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
